name: projetA62
on:
  push:
    branches:
      - main
      #- CML_plus_dvc 
jobs:
  CI_generate_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      
      - name: intstall_requirements
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
                    
      - name: upload data and setup neptune
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{secrets.NEPTUNE_PROJECT}}

        run: |
          dvc pull model
          ls -lrt model/
          export NEPTUNE_API_TOKEN="$NEPTUNE_API_TOKEN"
          export NEPTUNE_PROJECT="$NEPTUNE_PROJECT"

      - name: generate model and report.md
        run: |
          echo "# Metriques:" > report.md
          echo "# Matrice de Confusion:" > report2.md

          jupyter nbconvert --to notebook --execute notebook/iteration_4_generate_model_cnn.ipynb
          
          neptune mlflow

          #pip freeze > requirements_docker.txt
          #python --version > python_version.txt
          echo "   " >> report.md
          echo "   " >> report.md
          cat report2.md >> report.md          
          ls -lrt

      - name: send model to remote storage
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          #dvc add model
          #dvc push
          echo $(date +%Z)
          
      - name: preparer_gitpush
        run: |
          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git add requirements_docker.txt python_version.txt report.md
          #git add report.md model.dvc

          echo $(date +%Z)
          git commit --allow-empty -m "push model.dvc and report at $(date +%d-%b-%H_%M)"
          
          ################ ici attetion, changer la verions  #################
          
          #git tag -a "v2.3.1" -m "generate model in github, $(date +%Z), at $(date +%d-%b-%Y--%H_%M)"
          #git tag -a "v2.3.1" -m "generate model in github, $(date +%Z), at $(date +"%D--%T")"
          git tag -a "v2.3.2" -m "generate model in github, $(date +%Z), at $(date +%d-%b-%Y--%H:%M:%S)"
          
           
          #######################################################################################
          
          git push --follow-tags

          #################################
          # creer dossier app, add origin 2 et push model.dvc vers origin 2
        
        env:
          GITHUB_USERNAME: "$GITHUB_USERNAME"
          GITHUB_EMAIL: "$GITHUB_EMAIL"





          
                    
        